import { FunctionComponent } from 'react';
import {
  Box,
  Button,
  Flex,
  FormControl,
  FormLabel,
  Heading,
  Input,
  Text,
  Textarea,
} from '@chakra-ui/react';
import Head from 'next/head';
import { useForm } from 'react-hook-form';
import { yupResolver } from '@hookform/resolvers/yup';
import * as yup from 'yup';

interface IUserFormData {
  firstName: string;
  lastName: string;
  email: string;
  address: string;
  phone: number | undefined;
  description: string;
}

const schema = yup.object({
  firstName: yup.string().required('O primeiro nome é obrigatório'),
  lastName: yup.string().required('O sobrenome é obrigatório'),
  email: yup.string().email('E-mail inválido').required('O e-mail é obrigatório'),
  address: yup.string().required('O endereço é obrigatório'),
  phone: yup.string().transform(value => (value ? value.replace(/\D/g, '') : '')).matches(/^\d+$/, 'Digite apenas números').required('O telefone é obrigatório'),
  description: yup.string().required('A descrição é obrigatória'),
});

export const Cadastro: FunctionComponent = () => {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<IUserFormData>({
    resolver: yupResolver(schema),
  });

  const onSubmit = (data: IUserFormData) => {
    console.log(data);
  };

  return (
    <>
      <Head>
        <title>Formulários com NextJs e Chakra Ui</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Flex
          minHeight="100vh"
          width="full"
          align="center"
          justifyContent="center"
          backgroundColor="gray.900"
        >
          <Box
            px={12}
            py={12}
            width="full"
            maxWidth="450px"
            textAlign="center"
            boxShadow="lg"
            background="gray.700"
            borderRadius="6px"
          >
            <Heading>
              <Text color="gray.200" fontSize="2xl">
                Registro
              </Text>
            </Heading>
            <form
              action=""
              autoComplete="off"
              onSubmit={handleSubmit(onSubmit)}
            >
              <FormControl marginTop="15px">
                <FormLabel color="gray.200">Nome</FormLabel>
                <Input
                  type="text"
                  border="none"
                  outline="none"
                  bgColor="gray.900"
                  focusBorderColor="gray.600"
                  color="gray.200"
                  placeholder="Nome"
                  {...register('firstName')}
                />
                <p style={{ color: 'red' }}>{errors?.firstName?.message}</p>
              </FormControl>
              <FormControl marginTop="15px">
                <FormLabel color="gray.200">Sobrenome</FormLabel>
                <Input
                  type="text"
                  border="none"
                  outline="none"
                  bgColor="gray.900"
                  focusBorderColor="gray.600"
                  color="gray.200"
                  placeholder="Seu Sobrenome"
                  {...register('lastName')}
                />
                <p style={{ color: 'red' }}>{errors?.lastName?.message}</p>
              </FormControl>
              <FormControl marginTop="15px">
                <FormLabel color="gray.200">Seu e-mail</FormLabel>
                <Input
                  type="text"
                  border="none"
                  outline="none"
                  bgColor="gray.900"
                  focusBorderColor="gray.600"
                  color="gray.200"
                  placeholder="Seu Email"
                  {...register('email')}
                />
                <p style={{ color: 'red' }}>{errors?.email?.message}</p>
              </FormControl>
              <FormControl marginTop="15px">
                <FormLabel color="gray.200">Endereço</FormLabel>
                <Input
                  type="text"
                  border="none"
                  outline="none"
                  bgColor="gray.900"
                  focusBorderColor="gray.600"
                  color="gray.200"
                  placeholder="Seu Endereço"
                  {...register('address')}
                />
                <p style={{ color: 'red' }}>{errors?.address?.message}</p>
              </FormControl>
              <FormControl marginTop="15px">
                <FormLabel color="gray.200">Telefone</FormLabel>
                <Input
                  type="tel"
                  pattern="[0-9]*"
                  inputMode="numeric"
                  border="none"
                  outline="none"
                  bgColor="gray.900"
                  focusBorderColor="gray.600"
                  color="gray.200"
                  placeholder="Seu Telefone"
                  {...register('phone')}
                />
                <p style={{ color: 'red' }}>{errors?.phone?.message}</p>
              </FormControl>
              <FormControl marginTop="15px">
                <FormLabel color="gray.200">Mensagem</FormLabel>
                <Textarea
                  border="none"
                  outline="none"
                  bgColor="gray.900"
                  focusBorderColor="gray.600"
                  color="gray.200"
                  resize="none"
                  placeholder="Sua mensagem"
                  {...register('description')}
                />
                <p style={{ color: 'red' }}>{errors?.description?.message}</p>
              </FormControl>
              <Button
                type="submit"
                width="full"
                bgColor="green.400"
                mt={4}
                color="gray.200"
                _hover={{
                  color: 'black',
                }}
              >
                Registro com yup
              </Button>
            </form>
          </Box>
        </Flex>
      </main>
    </>
  );
};

export default Cadastro;
