import { FormEvent, FunctionComponent, useState } from 'react'
import {
  Box,
  Button,
  Flex,
  FormControl,
  FormLabel,
  Heading,
  Input,
  Text,
  Textarea
} from '@chakra-ui/react'
import Head from 'next/head'
import Link from 'next/link';

//tipando
interface IHomePops {
  fistName: string;
  lastName: string;
  email: string;
  phone: string;
  description: string;
}

  const Home: FunctionComponent<IHomePops> = () => {
  const [fistName, setFirstName] = useState('');
  const [lastName, setLastName] = useState('');
  const [email, setEmail] = useState('');
  const [address, setAddress] = useState('');
  const [phone, setPhone] = useState('');
  const [description, setDescription] = useState('');

  const handleSubmit = (e: FormEvent) => {
    e.preventDefault();

    const data = {
      fistName,
      lastName,
      email,
      address,
      phone,
      description
    }
    console.log(data);
  }

  return (
    <>
      <Head>
        <title>Formulários com NextJs e Chakra Ui</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Flex
          minHeight='100vh'
          width='full'
          align='center'
          justifyContent='center'
          backgroundColor='gray.900'
        >
          <Box
            px={12}
            py={12}
            width='full'
            maxWidth='450px'
            textAlign='center'
            boxShadow='lg'
            background='gray.700'
            borderRadius='6px'
          >
            <Heading>
              <Text color='gray.200' fontSize='2xl'>Registro</Text>
            </Heading>
            <Box>
              <Box autoComplete='off' onSubmit={handleSubmit} as='form'>
                <Flex justify='space-between'>
                  <FormControl marginTop='15px' width='49%'>
                    <FormLabel color='gray.200'>Primeiro nome</FormLabel>
                    <Input
                      type='text'
                      name='fistName'
                      border='none'
                      outline='none'
                      bgColor='gray.900'
                      focusBorderColor='gray.600'
                      color='gray.200'
                      placeholder='Primeiro nome'
                      onChange={(e) => setFirstName(e.target.value)}
                    />
                  </FormControl>
                  <FormControl marginTop='15px' width='49%'>
                    <FormLabel color='gray.200'>Sobrenome</FormLabel>
                    <Input
                      type='text'
                      name='lastName'
                      border='none'
                      outline='none'
                      bgColor='gray.900'
                      focusBorderColor='gray.600'
                      color='gray.200'
                      placeholder='Seu Sobrenome'
                      onChange={(e) => setLastName(e.target.value)}
                    />
                  </FormControl>
                </Flex>
                <FormControl marginTop='15px'>
                  <FormLabel color='gray.200'>Seu e-mail</FormLabel>
                  <Input
                    type='text'
                    name='email'
                    border='none'
                    outline='none'
                    bgColor='gray.900'
                    focusBorderColor='gray.600'
                    color='gray.200'
                    placeholder='Seu Email'
                    onChange={(e) => setEmail(e.target.value)}
                  />
                </FormControl>
                <Flex justify='space-between'>
                  <FormControl marginTop='15px' width='49%'>
                    <FormLabel color='gray.200'>Endereço</FormLabel>
                    <Input
                      type='text'
                      name='address'
                      border='none'
                      outline='none'
                      bgColor='gray.900'
                      focusBorderColor='gray.600'
                      color='gray.200'
                      placeholder='Seu Endereço'
                      onChange={(e) => setAddress(e.target.value)}
                    />
                  </FormControl>
                  <FormControl marginTop='15px' width='49%'>
                    <FormLabel color='gray.200'>Telefone</FormLabel>
                    <Input
                      type='text'
                      name='phone'
                      border='none'
                      outline='none'
                      bgColor='gray.900'
                      focusBorderColor='gray.600'
                      color='gray.200'
                      placeholder='Seu Telefone'
                      onChange={(e) => setPhone(e.target.value)}
                    />
                  </FormControl>
                </Flex>
                <FormControl marginTop='15px'>
                  <FormLabel color='gray.200'>Mensagem</FormLabel>
                  <Textarea
                    name='description'
                    border='none'
                    outline='none'
                    bgColor='gray.900'
                    focusBorderColor='gray.600'
                    color='gray.200'
                    resize='none'
                    placeholder='Sua mensagem'
                    onChange={(e) => setDescription(e.target.value)}
                  />
                </FormControl>
                <Button
                    type="submit"
                    width="full"
                    bgColor="green.400"
                    mt={4}
                    color="gray.200"
                    _hover={{
                      color: 'black'
                    }}
                    onClick={handleSubmit}
                  >
                    Registrar
                  </Button>
                <Link href="/cadastro">
                  <Button
                    type="button"
                    width="full"
                    bgColor="blue.400"
                    mt={4}
                    color="gray.200"
                    _hover={{
                      color: 'black'
                    }}
                  >
                   Passar para Página completa
                  </Button>
                </Link>
              </Box>
            </Box>
          </Box>
        </Flex>
    </>
  )
}

export default Home;
